### ISSUE TITLE
User can view all the tasks as a list

### ISSUE THREAD

**Issue by rodsonchue** [cs2103jan2015-w09-4j/main#36]
so that I can have an overview of what to do next

Implemented via `view` command #57

**Comment by rodsonchue** [comment]
CLIcommand: `display`
displays a list of all tasks sorted using the default sort option

**Comment by ericvader** [comment]
As discussed, the command should be:
`view: [agenda,weekly,monthly] [~{} -{}]`

agenda default time period - now to end of today
weekly deafult time period - previous monday to next sunday
monthly default time period - previous first to next 31/30/29/28

@rodsonchue change it to view!

**Comment by ericvader** [comment]
@chenhsin please implement the basic view, which is just "view" which is just view agenda. Implement by today so we get the v0.0 done!
