### ISSUE TITLE
Explicit parameter parsing v0.1

### ISSUE THREAD

**Issue by rodsonchue** [cs2103jan2015-w09-4j/main#45]
Leave a comment here if there is anything needed to be edited or is incorrect

__List of Affected Command keywords__

`add`
`modify`

__Possible command example(s)__

`add {Shopping} @{NUS} ~{tml} -{tml} !{tml} `~~`%10`~~` +{Buy 4pkt of Tao Suan for everyone}`~~`#food #cerclovestaosuan`~~
`modify Shopping +{Buy 5pkt of Tao Suan}`

__Task Parameters__

Parameter|Syntax Pattern|Additional Info
------------|--------------------|------------------
Title|~~Implicit Form: `add <phrase><SYMBOL>`~~|Form A and B are used for MODIFY operations
 |~~Form A: `=<word>`~~|E.g `modify Book ={Book of Thrones}`
 |Form B: `={<phrase>}`|
Location|~~Form A: `@<word>`~~|Typical use: Form A unless location is made up of more than one word.
 |Form B: `@{<phrase>}`|E.g `@{National University of Singapore}`
Deadline|Form A: `-{<time>}`|For deadline tasks
 |~~Form B: `-<word>`~~|Form B to support aliasing of words
 |~~Implicit: `by <time>`~~|E.g `-{tmr 3pm}`
Time Frame (to and from)|`~{<time>} -{<time>}`|For timed tasks which have a start and end time.
 |~~Implicit: `from ~{} to -{}`~~|E.g `~{tmr 2pm} -{tmr 3pm}`
~~Category (hashtag)~~|~~Form A: `#<word>`~~|~~Integrate ‘twitter mode’ into basic mode.~~
 |~~Form B: `#{<word>}`~~|~~Typical use: Form A but to also support Form B for consistency with other syntax~~
 | |~~E.g `add ={Buy tao suan} -{tmr 3pm} #ts`~~
 | |~~Should support multiple categories~~
Description|~~Form A: `+<word>`~~|2 forms to be consistent with all other syntax
 |Form B: `+{<phrase>}`|
Reminders|~~Form A: `!<word>`~~|E.g `add ={Buy tao suan} !{tmr 3pm}`
 |Form B: `!{<time>}`|
~~Priority~~|~~Form A: `%{<zeroToTen>}`~~|~~Priority levels: 0-10~~
 |~~Form B: `%<zeroToTen>`~~|~~Where 0 is lowest (green) and~~
 | |~~10 is highest (red for urgency)~~

__BNF Definitions__

`<phrase>:= <word> | <word><space><phrase> | <phrase><space><word>`
`<zeroToTen> := 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10`
~~**__`<SYMBOL> to be further discussed`__**~~

title, location, category, description: #71

**Comment by ericvader** [comment]
We will implement the explicit form for all the parameters, which will always be in the form `<SYMBOL>{<phrase>}`

The default parameter symbols will be:
+ Category: \#
+ Deadline: \-
+ Description: \+
+ Location: \@
+ Priority: \%
+ Reminder: \!
+ Title: \=
