### ISSUE TITLE
Implement view() function in Terminal.java

### ISSUE THREAD

**Issue by rodsonchue** [cs2103jan2015-w09-4j/main#49]
subtask of #51 

function should collect all tasks existing in the database, then display all their information with proper formatting through the active Display Object. Function is to be called upon by a Statement object to execute the required operation.

`view()` function should be `public` and ~~`static`~~ so as to support Statement objects accessing it on a particular Terminal Object. (there may exist more than one terminal)

function should throw an __CommandExecutionException__ back at Statement if there is problem with its execution

refer to the deprecated function `getAllTask()`, and replace it with this function once completed.

**Comment by ericvader** [comment]
Implementation complete, but has bugs
