### ISSUE TITLE
Implement Terminal.java basic functionality

### ISSUE THREAD

**Issue by rodsonchue** [cs2103jan2015-w09-4j/main#51]
Update (26/02/2015): added `help()` as part of the basic functionality package.

The class should interact with a Display object to produce an I/O interface with the user. (see #53 )

The class should provide basic database manipulation functions CRUD
`add()`: (testing) #47
`delete()`: (testing) #48 
`view()`: (testing) #49 
`modify()`: (testing) #50

The class should also provide helper functions to guide the user:
`help()`: (incomplete) #80 

The class should also create its own `Database` object to store all the tasks in. (pending close #55)

The class will be interacting primarily using `Task` objects. (pending close #52)

~~The class should also handle initialization and cleanup after the user is done using the program, such as to dump all task information in an external file.~~

~~The class should also store a 'Tree of past actions', with its second nodes being individual tasks so as to support the more powerful `undo` to be implemented in the later stages. Otherwise assume a relatively lower priority for now.~~

**Comment by chenhsin** [comment]
@ericvader Please write the the erroneous and the extreme test cases for Terminal.
