### ISSUE TITLE
Implement Task.java

### ISSUE THREAD

**Issue by rodsonchue** [cs2103jan2015-w09-4j/main#52]
__Update notes (02/25/2015):__
* __[pending accept]__ To standardize how object is initialised, a Task object is to be constructed using a `default constructor` i.e without any parameters.
* Make sure to inform others whom are currently using Task objects to follow such a construction.
* __[pending accept]__ Add another `public` ~~`static`~~ function `getTaskType()` which returns a enumeration `TaskType` of the current object. This function should __not__ directly return the `TaskType` enumeration but also to check all its variables to ensure that the TaskType still makes sense. E.g if the object's `startDate` and `endDate` is set to null, then the `TaskType` should not be `Timed`, but `FLOATING` or `INCOMPLETE`. This is important because the Task setters/getters are publicly accessible.

-------------------------------------------------

__Update notes: inline with @ericvader proposed changes__

Class should provide static constructors for specific task types such as
`createDeadlineTask` `createFloatingTask` `createTimedTask` `createIncompleteTask`

An instance of the object is defined with the following variables and their respective set/get-ters:

enum `TaskType` lists out all possible tasks which includes
* `DEADLINE`
* `FLOATING`
* `TIMED`
* `INCOMPLETE`

`title` as a String representing the title of the task

`description` as a String representing the description of the task

`priority` as an Integer representing the priority level of the task

Use [java.Date](http://docs.oracle.com/javase/8/docs/api/java/util/Date.html) to implement:
* `startDate` and `endDate` variables representing the Time frame. Deadline Tasks should also make use of these variables.
* `reminder` represents when the user wants to be reminded of the task.

`category` as a String representing which category the Task belongs to.

`done` as a boolean representing whether Task is completed or not.

---------------------------------------

A task should also contain a __LinkedList<Task>__ where it stores a sequential history of its changes including its __Initial Instance__ so as to support power undo functionality (See #11 )

Implement an `void update()` function which takes in a Task object and updates __this__ Task with the given delta information (devise a method to extract)

**Comment by ericvader** [comment]
I suggest using the names stated in our documentation:
+ Title
+ Location
+ Deadline
+ Time Frame (to and from)
+ Affiliation (hashtag)
+ Description
+ Reminders
+ Priority

It should have a function to determine which type of task it is(which the types should be classified as an enum):
+ timed tasks
+ deadlines
+ floating tasks

Also, it should have a update function which takes in another Task and updates the current one. I suggest assigning this to @chenhsin

**Comment by rodsonchue** [comment]
alright we will leave it up to @chenhsin to handle Task.java

**Comment by rodsonchue** [comment]
Since Task.java now has an update() function, taskMap in Terminal.java is obsolete and should be removed since its not going to be used

**Comment by rodsonchue** [comment]
please review the recommended updates @chenhsin

**Comment by chenhsin** [comment]
@rodsonchue okay noted.
