### ISSUE TITLE
Parsing of the command

### ISSUE THREAD

**Issue by ericvader** [cs2103jan2015-w09-4j/main#57]
Commands supported:
+ add: Adds a task to the task manager. It can add floating task #38 , deadline task #37 , timed task #21 , ~~recurring deadline task or recurring timed task.~~ #70
+ alias: List all the aliases in the database.#65
+ alias-add: Adds a new alias to the database.#69
+ alias-delete: Deletes a alias from the database.#69
+ delete: Deletes a task and moves it to the tasks recycle bin. #20 #66
+ done: Done command is run when the task is completed.#66
+ exit: Exits the task manager.#65
+ history: Displays the current history of actions. #6 #65
+ history-clear: Clears one~~, a range or all~~ history. #68
+ history-undo: Undo one history action. #11 #68
+ modify: Modifies the task specified, updating the details of the tasks. #19 #70
+ search: Search for a particular task in the task manager. #25 #70
+ view: Lists the tasks in the task manager, giving the option to display in different formats. #12 #36 
+ help: Display help messages. #43 #65

**Comment by chenhsin** [comment]
@rodsonchue Please write the the erroneous and the extreme test cases for Command.
