### ISSUE TITLE
Bug: Update AddStatement.java

### ISSUE THREAD

**Issue by rodsonchue** [cs2103jan2015-w09-4j/main#77]
As the function `add(Task)` now throws Exceptions, `addStatement` needs to catch them.
Exceptions thrown are as follows:
* CommandExecutionException: thrown when taskMap update goes wrong.
* Exception: any other kind of exceptions which are thrown from Database object (due to add failure)

**Comment by ericvader** [comment]
I think all Terminal 'execution' functions (add, modify, ...) should throw CommandExecutionException to be consistent. means that if there are any problems, it will throw that.

And also i think CommandExecutionException should be CommandExecuteException

**Comment by ericvader** [comment]
And also i think You should come up with a interface class to define all the public API of the Terminal. all the add, modify, etc...

**Comment by rodsonchue** [comment]
Noted. Will create another issue regarding the interface. 
* `CommandExecutionException` refactored to `CommandExecuteException`
* `Terminal.java`: `add(Task)` and `modify(String, Task)` now only throws `CommandExecuteException` instead of `Exception` previously

**Comment by ericvader** [comment]
(Y) Thanks! Once you are done then i will fix my part!
