### ISSUE TITLE
User can use the Basic command format to enter a task

### ISSUE THREAD

**Issue by ericvader** [cs2103jan2015-w09-4j/main#9]
So that the user will not need to use the GUI at all to specify the fields.

The basic command format parsing consist of 2 parts: parsing of the command and parsing of the parameters. 

For the command, there are 2 forms of the command, Explicit(add) and also Implicit(A). Moreover add is always implied when there is no command.

For parameters there are 3 forms, Explicit, Explicit without {} and Implicit(only applicable to some parameters)

Refer to subtasks:
Parsing of the command:
 + 
Parsing of the parameters: 
+ Explicit: #45 
+ Explicit without {}: 
+ Implicit:

**Comment by ericvader** [comment]
Floating task: add <TASK_NAME>
Deadline task: add <TASK_NAME> -D <DATE>
Timed task: add <TASK_NAME> -D <DATE> -T <TIME>
Timed task(w start and end)aka event: add <TASK_NAME> -D <DATE> -ST <TIME> -ET <TIME>
Recurring tasks: add <TASK_NAME> -RE <TYPE_OF_REC> <VAL> -T <TIME> -ST <TIME> -ET <TIME>
Modify task: modify <TASK_NAME/_ID> <?>
List task: list <done/undone> -SN <TAG_SET_NOTATION> -S <Field>
Search List: search <?> -S <done/undone> -SN <TAG_SET_NOTATION>
Delete List: delete <?> -S <done/undone> -SN <TAG_SET_NOTATION>
History: history
Clear: clear <history_id[]/all>

**Comment by chenhsin** [comment]
Hi, i think the commands are not user friendly

**Comment by ericvader** [comment]
Well, our tutors from CS2103 think so too. In light of this we should simplify the basic command to have a more intuitive syntax. Also, I think we should only have 1 command format, we should close issues #8 and #10! If we have time we can revisit #10 later. 

How about we think of a tagging system where like @\{location\} and other symbols for other fields?

**Comment by chenhsin** [comment]
Yea, we should close both of them.

Alright! I think symbols are easier to relate.

**Comment by rodsonchue** [comment]
How about this?
`<phrase>:= <word> | <space><phrase> | <phrase><space>`
`<zeroToTen> := 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10`
**__`<SYMBOL> to be further discussed`__**

Parameter|Syntax Forms|Additional Info
-------------|------------------|------------------
Title|Implicit Form: `add <phrase>  <SYMBOL>`|Form A and B are used for MODIFY operations
 |Form A: `=<word>`|E.g `modify Book ={Book of Thrones}`
 |Form B: `={<phrase>}`|
Location|Form A: `@<word>`|Typical use: Form A unless location is made up of more than one word.
 |Form B: `@{<phrase>}`|E.g `@{National University of Singapore}`
Deadline|Form A: `-{<time>}`|For deadline tasks
 |Form B: `-<word>`|Form B to support aliasing of words
 |Implicit: by t|E.g `-{tmr 3pm}`
Time Frame (to and from)|`~{<time>} -{<time>}`|For timed tasks which have a start and end time.
 |Implicit: `from ~{} to -{}`|E.g `~{tmr 2pm} -{tmr 3pm}`
Affiliation (hashtag)|Form A: `#<word>`|Integrate ‘twitter mode’ into basic mode. 
 |Form B: `#{<word>}`|Typical use: Form A but to also support Form B for consistency with other syntax
 | |E.g `add ={Buy tao suan} -{tmr 3pm} #ts`
Description|Form A: `+<word>`|2 forms to be consistent with all other syntax
 |Form B: `+{<phrase>}`|
Reminders|Form A: `!<word>`|E.g `add {Buy tao suan} !{tmr 3pm}`
 |Form B: `!{<time>}`|
Priority|Form A: `%{<zeroToTen>}`|Priority levels: 0-10
 |Form B: %<zeroToTen>|Where 0 is lowest (green) and
 | |10 is highest (red for urgency)

**Comment by imchenchen1994** [comment]
Ya, I think 1 mode is enough for user to use. It should be more user friendly.

**Comment by ericvader** [comment]
Okay, Approved!
