### ISSUE TITLE
Change in architecture API: Terminal <> Display Interaction

### ISSUE THREAD

**Issue by rodsonchue** [cs2103jan2015-w09-4j/main#93]
The API originally used a `String` for both input and output
Post discussion changes have indicated that it would be better to use an `InputStream`, to prevent front end processing from holding back what is going on in the back end.
Affected components include: `Display` `CLIDisplay` `GUIDisplay` `Terminal`

**Comment by ericvader** [comment]
Code errornously factored at start, not Terminal
